name: shopping_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  geolocator: ^11.1.0
  geocoding: ^3.0.0
  provider: ^6.0.5
  google_fonts: ^6.2.0
  iconsax: ^0.0.8
  easy_localization: ^3.0.5
  flutter_screenutil: ^5.9.0
  awesome_dialog: ^3.2.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_2.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
